
// 389. Find the Difference  |  Platform : LeetCode


// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.


// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// Example 2:
// Input: s = "", t = "y"
// Output: "y"
 

// Constraints:
// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.




#include<iostream>
#include<unordered_map>
using namespace std;

char findTheDifference(string s, string t) {
    unordered_map<char,int> freqS;
    for ( char ch : s ) {
        freqS[ch]++;
    }

    for ( char ch : t ) {
        if ( freqS[ch] == 0 ) {
            return ch;
        }
        freqS[ch]--;
    }

    return ' ';
}

int main() {
    string s = "abcd", t = "abcde";
    cout << findTheDifference(s,t);
    return 0;
}